version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: job-platform-mongo
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: job-platform

  redis:
    image: redis:7-alpine
    container_name: job-platform-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  meilisearch:
      image: getmeili/meilisearch:v1.7
      container_name: job-platform-meilisearch
      restart: unless-stopped
      ports:
        - '7700:7700'
      volumes:
        - meili_data:/meili_data
      environment:
        MEILI_MASTER_KEY: masterKey123
        MEILI_ENV: development

volumes:
  mongo_data:
  redis_data:
  meili_data: